repos:
  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements

  # Keep setup.cfg clean
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt

  # Adds a standard feel to import segments
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  # Format code.
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black

  # Format docs. No, I don't like everything black does either.
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]

  # Flake8 for linting, line-length adjusted to match Black default
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length, "88"]

  # Type enforcement for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  # Security checks for python code
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        # Skip asserts and HTTP.client
        args: [--skip, "B101,B309"]
