repos:
  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements

  # Adds a standard feel to import segments, adds future annotations
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--py37-plus"
          - "--add-import"
          - "from __future__ import annotations"
          - "--application-directories"
          - ".:src"

  # Automatically upgrade syntax to newer versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"

  # Format code. No, I don't like everything black does either.
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # Format docs.
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.14.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=23.3.0]

  # Flake8 for linting, line-length adjusted to match Black default
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-builtins
          - flake8-pep585
        args:
          - "--ignore"
          - "W503,E203"
          - "--max-line-length"
          - "88"

  # Type enforcement for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
