repos:
  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements

  # Keep setup.cfg clean
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
      - id: setup-cfg-fmt

  # Adds a standard feel to import segments, adds future annotations
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]

  # Automatically upgrade syntax to newer versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  # Format code. No, I don't like everything black does either.
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  # Format docs.
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=21.12b0]

  # Flake8 for linting, line-length adjusted to match Black default
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-builtins]
        args:
          - --ignore=W503,E203
          - --max-line-length=88

  # Type enforcement for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
